DESCRIPTION = "Build external dependencies for use in CPAN"

SECTION = "libs"
LICENSE = "GPL-1.0-or-later | Artistic-1.0"

PACKAGE_NAME=	"Alien-Build"
MAINTAINER=	"M4SS <edoardo.morandi@m4ss.net>"
HOMEPAGE=	"https://metacpan.org/dist/${PACKAGE_NAME}"

LIC_FILES_CHKSUM = "file://LICENSE;md5=3f954fe1589181942a319bbb4c8e1334"

BASE_SRC_URI = "https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/${PACKAGE_NAME}"
SRC_URI[sha256sum] = "8e891fd3acbac39dd8fdc01376b9abff931e625be41e0910ca30ad59363b4477"

SRC_URI = "${BASE_SRC_URI}-${PV}.tar.gz"
S = "${WORKDIR}/${PACKAGE_NAME}-${PV}"

UPSTREAM_CHECK_URI = "${HOMEPAGE}"
UPSTREAM_CHECK_REGEX = "${BASE_SRC_URI}-(?P<pver>\d+(\.\d+){1,2})\.tar\.gz"

inherit cpan

DEPENDS += "file-which-perl-native"

RDEPENDS:${PN} += "capture-tiny-perl"
RDEPENDS:${PN} += "perl-module-digest-sha"
RDEPENDS:${PN} += "perl-module-extutils-cbuilder"
RDEPENDS:${PN} += "perl-module-extutils-makemaker"
RDEPENDS:${PN} += "perl-module-extutils-parsexs"
RDEPENDS:${PN} += "ffi-checklib-perl"
RDEPENDS:${PN} += "file-which-perl"
RDEPENDS:${PN} += "file-chdir-perl"
RDEPENDS:${PN} += "perl-module-json-pp"
RDEPENDS:${PN} += "perl-module-list-util"
RDEPENDS:${PN} += "path-tiny-perl"
RDEPENDS:${PN} += "perl-module-test2-api"
RDEPENDS:${PN} += "perl-module-text-parsewords"
RDEPENDS:${PN} += "perl-module-parent"
RDEPENDS:${PN} += "perl-module-carp"
RDEPENDS:${PN} += "pkgconfig"
RDEPENDS:${PN} += "perl-module-env"
RDEPENDS:${PN} += "pkgconfig-perl"
RDEPENDS:${PN} += "env-shellwords-perl"
RDEPENDS:${PN} += "file-listing-perl"
RDEPENDS:${PN} += "uri-perl"
RDEPENDS:${PN} += "html-parser-perl"
# RDEPENDS:${PN} += "file-listing-ftpcopy-perl"
RDEPENDS:${PN} += "mojo-dom58-perl"
RDEPENDS:${PN} += "mojolicious-perl"
RDEPENDS:${PN} += "archive-zip-perl"
RDEPENDS:${PN} += "perl-module-archive-tar"
RDEPENDS:${PN} += "perl-module-io-zlib"
RDEPENDS:${PN} += "perl-module-io-compress-bzip2"
RDEPENDS:${PN} += "io-compress-lzma-perl"
RDEPENDS:${PN} += "http-tiny-perl"
RDEPENDS:${PN} += "mozilla-ca-perl"
RDEPENDS:${PN} += "perl-module-net-ftp"
RDEPENDS:${PN} += "lwp-protocol-https-perl"
RDEPENDS:${PN} += "libwww-perl-perl"
RDEPENDS:${PN} += "curl"
RDEPENDS:${PN} += "wget"
# RDEPENDS:${PN} += "pkgconfig-libpkgconf-perl"
RDEPENDS:${PN} += "sort-versions-perl"
RDEPENDS:${PN} += "perl-module-extutils-cbuilder"
# TODO: conditionally depend on this on Windows
# RDEPENDS:${PN} += "alien-msys-perl"
# RDEPENDS:${PN} += "alien-cmake3-perl"
# RDEPENDS:${PN} += "alien-gmake-perl"
# RDEPENDS:${PN} += "digest-sha-pureperl-perl"
# RDEPENDS:${PN} += "alien-gzip-perl"
# RDEPENDS:${PN} += "alien-libbz-perl"
# RDEPENDS:${PN} += "alien-unzip-perl"
# RDEPENDS:${PN} += "alien-xz-perl"

BBCLASSEXTEND = "native"
